;;; test-init-session.el --- Tests for init-session -*- lexical-binding: t; -*-

(require 'ert)
(require 'init-config)
(require 'init-session)

(ert-deftest rivenEmacs-session-test-directory-setup ()
  (should (stringp rivenEmacs-session-directory))
  (should (file-name-absolute-p rivenEmacs-session-directory)))

(ert-deftest rivenEmacs-session-test-customization-types ()
  (should (boundp 'rivenEmacs-session-directory))
  (should (boundp 'rivenEmacs-session-auto-save-interval))
  (should (boundp 'rivenEmacs-session-default-session))
  (should (boundp 'rivenEmacs-session-save-geometry))
  (should (boundp 'rivenEmacs-session-show-in-modeline))
  (should (stringp rivenEmacs-session-directory))
  (should (or (integerp rivenEmacs-session-auto-save-interval)
              (null rivenEmacs-session-auto-save-interval)))
  (should (stringp rivenEmacs-session-default-session))
  (should (booleanp rivenEmacs-session-save-geometry))
  (should (booleanp rivenEmacs-session-show-in-modeline)))

(ert-deftest rivenEmacs-session-test-helper-functions-exist ()
  (should (fboundp 'rivenEmacs-session-ensure-directory))
  (should (fboundp 'rivenEmacs-session-default-predicate))
  (should (fboundp 'rivenEmacs-session-setup-empty)))

(ert-deftest rivenEmacs-session-test-predicate ()
  (let ((easysession--current-session-name nil))
    (should-not (rivenEmacs-session-default-predicate)))
  (let ((easysession--current-session-name "main"))
    (should (rivenEmacs-session-default-predicate)))
  (let ((easysession--current-session-name "temp-test"))
    (should-not (rivenEmacs-session-default-predicate))))

(ert-deftest rivenEmacs-session-test-easysession-commands-available ()
  (should (fboundp 'easysession-switch-to))
  (should (fboundp 'easysession-save-as))
  (should (fboundp 'easysession-save))
  (should (fboundp 'easysession-load))
  (should (fboundp 'easysession-load-including-geometry))
  (should (fboundp 'easysession-delete))
  (should (fboundp 'easysession-rename))
  (should (fboundp 'easysession-save-mode))
  (should (fboundp 'easysession-get-current-session-name)))

(ert-deftest rivenEmacs-session-test-default-values ()
  (should (equal rivenEmacs-session-default-session "main"))
  (should (equal rivenEmacs-session-auto-save-interval 300))
  (should rivenEmacs-session-save-geometry)
  (should rivenEmacs-session-show-in-modeline))

(ert-deftest rivenEmacs-session-test-integration ()
  (should (featurep 'init-session))
  (should (featurep 'init-config)))

(ert-deftest rivenEmacs-session-test-keymap-exists ()
  (should (boundp 'rivenEmacs-session-map))
  (should (keymapp rivenEmacs-session-map)))

(ert-deftest rivenEmacs-session-test-global-keybinding ()
  (let ((binding (lookup-key global-map (kbd "C-c s"))))
    (should binding)
    (should (keymapp binding))))

(ert-deftest rivenEmacs-session-test-keymap-bindings ()
  (let ((map rivenEmacs-session-map))
    (should (lookup-key map (kbd "s")))
    (should (lookup-key map (kbd "S")))
    (should (lookup-key map (kbd "l")))
    (should (lookup-key map (kbd "L")))
    (should (lookup-key map (kbd "d")))
    (should (lookup-key map (kbd "r")))
    (should (lookup-key map (kbd ".")))
    (should (lookup-key map (kbd "c")))
    (should (eq (lookup-key map (kbd "s")) #'easysession-switch-to))
    (should (eq (lookup-key map (kbd "S")) #'easysession-save-as))
    (should (eq (lookup-key map (kbd "l")) #'easysession-load))
    (should (eq (lookup-key map (kbd "L")) #'easysession-load-including-geometry))
    (should (eq (lookup-key map (kbd "d")) #'easysession-delete))
    (should (eq (lookup-key map (kbd "r")) #'easysession-rename))
    (should (eq (lookup-key map (kbd ".")) #'easysession-save))
    (should (eq (lookup-key map (kbd "c")) #'easysession-get-current-session-name))))

(ert-deftest rivenEmacs-session-test-hooks-registered ()
  (should (member #'rivenEmacs-session-setup-empty easysession-new-session-hook))
  (should (member 'easysession-save-mode emacs-startup-hook)))
