;;; keybindings-spec-core.el --- Core keybinding specs -*- lexical-binding: t; -*-

(defvar riven/keybindings-leader-spec-core
  '(("f" "File"
     (("f" consult-fd "Find file")
      ("F" +consult-fd-in-home "Find file from home")
      ("r" consult-recent-file "Recent file")
      ("d" crux-recentf-find-directory "Recent directory")
      ("s" deadgrep "Search file contents")
      ("g" consult-git-grep "Git grep file contents")
      ("b" ibuffer-list-buffers "List buffers")
      ("p" riven/keybindings-copy-current-file-path "Copy current file path")
      ("n" riven/keybindings-rename-current-file-or-buffer "Rename file or buffer")
      ("D" riven/keybindings-delete-current-file-or-buffer "Delete file or buffer")
      ("R" revert-buffer-quick "Revert buffer")
      ("e" set-buffer-file-coding-system "Set file encoding")
      ("m" bookmark-set "Bookmark")
      ("h" vundo "Buffer history")))

    ("p" "Project"
     (("p" project-switch-project "Switch project")
      ("f" project-find-file "Find project file")
      ("b" consult-project-buffer "Project buffers")
      ("s" consult-ripgrep-ex "Search project text")
      ("g" consult-git-grep "Git grep project")
      ("r" color-rg-search-symbol-in-project "Search/replace in project")
      ("c" +remove-invalidate-buffers "Clean invalid buffers")
      ("z" project-forget-zombie-projects "Forget zombie projects")
      ("d" riven/keybindings-project-dired "Project Dired")))

    ("s" "Search"
     (("l" consult-line "Search line")
      ("i" consult-imenu "Imenu")
      ("o" consult-outline "Outline")
      ("m" consult-mark "Mark")
      ("M" consult-global-mark "Global mark")
      ("c" avy-goto-char-2 "Goto char")
      ("k" consult-keep-lines "Keep matching lines")
      ("u" consult-focus-lines "Focus matching lines")
      ("h" riven/keybindings-symbol-overlay-dispatch "Highlight/search symbol")
      ("/" consult-ripgrep "Ripgrep")))

    ("g" "Git"
     (("g" magit-status "Status")
      ("b" magit-blame "Blame")
      ("d" magit-diff-dwim "Diff")
      ("l" magit-log "Log")
      ("c" magit-clone "Clone")
      ("i" magit-init "Init")
      ("s" magit-stage "Stage")
      ("h" diff-hl-show-hunk "Show hunk")
      ("n" diff-hl-next-hunk "Next hunk")
      ("p" diff-hl-previous-hunk "Previous hunk")
      ("t" git-timemachine-toggle "Time machine")))

    ("c" "Code"
     (("d" riven/xref-find-definitions-or-search "Find definition")
      ("D" riven/eglot-find-declaration-dispatch "Find declaration")
      ("r" xref-find-references "Find references")
      ("i" eglot-find-implementation "Find implementation")
      ("t" riven/eglot-find-type-definition-dispatch "Find type definition")
      ("a" eglot-code-actions "Code action")
      ("f" riven/eglot-format-dispatch "Format buffer")
      ("R" eglot-rename "Rename symbol")
      ("k" sp-kill-whole-line "Kill smart line")
      ("s" sp-splice-sexp "Splice sexp")
      ("w" sp-rewrap-sexp "Rewrap sexp")
      ("q" quickrun "Quickrun")))

    ("e" "Error"
     (("l" riven/flymake-show-buffer-diagnostics-focus "List diagnostics")
      ("n" flymake-goto-next-error "Next error")
      ("p" flymake-goto-prev-error "Previous error")
      ("s" flymake-start "Start checker")
      ("v" flymake-switch-to-log-buffer "View checker log")
      ("f" eslint-fix "Fix with ESLint")))

    ("t" "Tool"
     (("t" ghostel "Terminal")
      ("d" docker "Docker")
      ("r" reader-open-doc "Reader")
      ("n" elfeed "News")
      ("q" quickrun "Quickrun")
      ("D" devdocs-lookup "DevDocs")
      ("." fanyi-dwim "Dictionary")
      ("m" woman "Manual")
      ("g" riven/google-search "Google search")
      ("T" riven/google-translate "Google translate")
      ("o" +open-in-system-explorer "Open in system explorer")))

    ("w" "Window"
     (("s" split-window-below "Split below")
      ("v" split-window-right "Split right")
      ("d" delete-window "Delete window")
      ("o" delete-other-windows "Delete other windows")
      ("w" other-window "Other window")
      ("b" balance-windows "Balance windows")
      ("u" winner-undo "Winner undo")
      ("r" winner-redo "Winner redo"))))
  "Core declarative specs for structured `C-c' groups.")

(defvar riven/keybindings-navigate-spec
  '(("c" avy-goto-char-2 "Goto Char")
    ("g" consult-goto-line "Line")
    ("i" consult-imenu "Imenu")
    ("l" link-hint-open-link "Link")
    ("o" consult-outline "Outline")
    ("m" consult-mark "Mark")
    ("M" consult-global-mark "Global Mark")
    ("n" next-error "Next Error")
    ("p" previous-error "Prev Error")
    ("[" diff-hl-previous-hunk "Previous Hunk")
    ("]" diff-hl-next-hunk "Next Hunk"))
  "Declarative specs for `navigate-leader-def`.")

(provide 'keybindings-spec-core)
