;;; Automatically generated by ‘recentf’ on Sat Mar  7 22:24:01 2026  -*- mode: emacs-lisp; lexical-binding: t -*-

(setq recentf-list
      '(
        "/Users/riven/Github/RivenEmacs/lisp/local/dape-breakpoints"
        "/Users/riven/Github/opentui/packages/react/jsx-runtime.js"
        "/Users/riven/Github/opentui/packages/react/newFile.js"
        "/Users/riven/Github/opentui/packages/core/package.json"
        "/Users/riven/Github/opentui/packages/core/src/3d.ts"
        "/Users/riven/Github/RivenEmacs/lisp/ide/init-lsp-bridge.el"
        "/Users/riven/.emacs.d/elpa/lsp-bridge/acm/acm-backend-lsp.el"
        "/Users/riven/Github/RivenEmacs/lisp/completion/init-consult.el"
        "/Users/riven/Github/RivenEmacs/lisp/keymaps/keybindings-spec-core.el"
        "/Users/riven/Github/RivenEmacs/lisp/core/init-config.el"
        "/Users/riven/Github/opentui/scripts/pre-publish.ts"
        "/Users/riven/Github/RivenEmacs/lisp/keymaps/init-keybindings.el"
        "/Users/riven/Github/opentui/packages/react/examples/diff.tsx"
        "/Users/riven/Github/RivenEmacs/lisp/ai/init-prompt-template.el"
        "/Users/riven/Github/RivenEmacs/lisp/ai/init-gpt-helper.el"
        "/Users/riven/Github/RivenEmacs/lisp/ai/init-gpt.el"
        "/Users/riven/Github/opentui/packages/react/jsx-runtime.d.ts"
        "/Users/riven/Github/opentui/packages/react/jsx-dev-runtime.js"
        "/Users/riven/Github/HugoBlog/public/index.xml"
        "/Users/riven/Github/RivenEmacs/lisp/env.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
