;;; Automatically generated by ‘recentf’ on Sat Mar  7 17:55:51 2026  -*- mode: emacs-lisp; lexical-binding: t -*-

(setq recentf-list
      '(
        "~/Github/RivenEmacs/lisp/local/dape-breakpoints"
        "~/Github/RivenEmacs/lisp/ai/init-prompt-template.el"
        "~/Github/RivenEmacs/lisp/ai/init-gpt-helper.el"
        "~/Github/RivenEmacs/lisp/ai/init-gpt.el"
        "~/Github/opentui/packages/react/jsx-runtime.js"
        "~/Github/opentui/packages/react/jsx-runtime.d.ts"
        "~/Github/opentui/packages/react/jsx-dev-runtime.js"
        "~/Github/HugoBlog/public/index.xml"
        "~/Github/RivenEmacs/lisp/env.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
