;; -*- mode: emacs-lisp; lexical-binding: t; coding: utf-8-emacs-unix -*-
;; Minibuffer history file, automatically generated by â€˜savehistâ€™.

(setq savehist-minibuffer-history-variables '(buffer-name-history consult--buffer-history minibuffer-history consult--grep-history project--dir-history file-name-history extended-command-history))
(setq buffer-name-history '(
;;;  #<buffer init-gpt.el>
 "*DeepSeek*"))
(setq consult--buffer-history '("init-gpt.eløˆ€€€" "*dashboard*øˆ€€€"))
(setq minibuffer-history '("zh" "zh-cn" "zh" "zh-cn"))
(setq consult--grep-history '("#import"))
(setq file-name-history '("~/Github/RivenEmacs/lisp/ai/agent-shell/" "~/Github/RivenEmacs/lisp/ai/init-gpt-helper.el" #("/Users/riven/Github/RivenEmacs/lisp/ai/init-gpt.el" 0 50 (project "~/Github/RivenEmacs/")) "~/Github/RivenEmacs/" "~/Github/opentui/packages/react/jsx-runtime.js" "~/Github/opentui/packages/react/" "~/Github/RivenEmacs/lisp/local/dape-breakpoints" "~/Github/opentui/" #("/Users/riven/Github/HugoBlog/public/index.xml" 0 45 (project "~/Github/HugoBlog/")) "~/Github/HugoBlog/" "~/Github/RivenEmacs/"))
(setq extended-command-history '("restart-emacs"))
