;; -*- mode: emacs-lisp; lexical-binding: t; coding: utf-8-emacs-unix -*-
;; Minibuffer history file, automatically generated by â€˜savehistâ€™.

(setq savehist-minibuffer-history-variables '(consult--buffer-history minibuffer-history consult--grep-history project--dir-history file-name-history extended-command-history))
(setq consult--buffer-history '("*dashboard*øˆ€€€"))
(setq consult--grep-history '("#import"))
(setq file-name-history '("~/Github/opentui/packages/react/jsx-runtime.js" "~/Github/opentui/packages/react/" "~/Github/RivenEmacs/lisp/local/dape-breakpoints" "~/Github/opentui/" #("/Users/riven/Github/HugoBlog/public/index.xml" 0 45 (project "~/Github/HugoBlog/")) "~/Github/HugoBlog/" "~/Github/RivenEmacs/"))
(setq extended-command-history '("restart-emacs"))
